In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [14]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.ones((4,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [22]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [24]:
np.random.rand(5,5)

array([[ 0.16187687,  0.65948663,  0.05342647,  0.31962153,  0.80654058],
       [ 0.03907285,  0.83284758,  0.64645153,  0.05918727,  0.42596071],
       [ 0.87741183,  0.78494025,  0.78044494,  0.46083996,  0.13609884],
       [ 0.86478851,  0.90237339,  0.56763823,  0.79838532,  0.721435  ],
       [ 0.81511906,  0.08187357,  0.48451489,  0.07905354,  0.06169623]])

In [25]:
np.random.randn(2)

array([ 0.3649881 ,  1.63722328])

In [27]:
np.random.randint(0,100,10)

array([75, 74,  8, 95, 43, 44,  4,  2, 89, 20])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([ 7, 25, 37, 45,  5, 37, 13, 14, 25, 11])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr

array([ 7, 25, 37, 45,  5, 37, 13, 14, 25, 11])

In [36]:
ranarr.reshape(2,5)

array([[ 7, 25, 37, 45,  5],
       [37, 13, 14, 25, 11]])

In [37]:
ranarr.max()

45

In [38]:
ranarr.min()

5

In [39]:
ranarr

array([ 7, 25, 37, 45,  5, 37, 13, 14, 25, 11])

In [40]:
ranarr.argmax()

3

In [41]:
ranarr.argmin()

4

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int64')